# Generated by Django 4.2.11 on 2025-04-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Extensao', '0002_curso_delete_todoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
