# Generated by Django 4.2.11 on 2025-04-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Extensao', '0003_alter_curso_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='anotacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
